### ISSUE TITLE
JSON output metadata contents

### ISSUE THREAD

**Issue by davwheat** [HandyMenny/uecapabilityparser#151]
For B826 packets, the current JSON output format provides metadata for each individual packet by appending the index to the JSON key.

I think it would be better to provide this separately to the generic metadata about the parser, timestamp, processing time, etc.

Potentially, `metadata` could have `generic`/`common` and `formatSpecific` keys to handle this. This would make metadata output easier to work with when handling a variety of different formats.

It may also be worth providing the packet metadata either in an array (not sure if this could cause issues for missing packets?) or perhaps in a JSON object with stringified numbers for keys instead `{ "1": { "logSize": "1234", "version": "10", ... }`.

What's your opinion on this?

**Comment by HandyMenny** [comment]
The sense of "metadata" is to have a dictionary in which I can enter values that might be useful for debugging purposes without worrying about their structure. That is, they aren't meant to be stable, they don't have a specific format. Implemented in this way I avoid any problems in serializing/deserializing json when the keys change.

if you think any of these values might be critical for post-processing, I can "stabilize" them in a dedicated field.

For the second question I'm against further structuring the metadata section.
But I haven't really decided yet how to handle multiple-capabilities. At the moment it's a bit mixed, there're parsers that don't support multiple capabilities (UE Capability Information, 28874 Nvitem), there're parsers that natively support multiple capabilities (Carrier policy, nr cap prune, mtk ca_comb_info, 0xb0cd) and others that have support for multiple inputs in the "gluing" code (0xB826 you mentioned).

**Comment by HandyMenny** [comment]
Here there's another approach to handle multi-log metadata: https://github.com/HandyMenny/uecapabilityparser/pull/258

The shortcomings are:
- if the logs have different metadata sets they may no longer be aligned
- it is necessary to manually split each metadata value

The advantages are:
- the metadata structure remains simple
- you no longer have to search for all possible indexes

Feedback would be much appreciated :)
