### ISSUE TITLE
Invalid input data results in exit code 0

### ISSUE THREAD

**Issue by davwheat** [HandyMenny/uecapabilityparser#166]
At the moment, if you provide garbage data to the parser, it exits with exit code 0, indicating success.

Could this change to a non-zero code to indicate a failure, or some other indicator in the output (e.g., success field in metadata for JSON, etc?)

**Comment by HandyMenny** [comment]
At the moment error handling is practically non-existent, just a couple of try catches...

But the answer to your question depends on what you mean by invalid data. An UE Capability Information without eutra/eutra-nr/nr is invalid data?
A carrier policy without combos is invalid data?
In any case I don't like to complicate the output with error/succes fields, the api will probably return a 5xx or 4xx code instead of 200 in these cases.

**Comment by davwheat** [comment]
> But the answer to your question depends on what you mean by invalid data. An UE Capability Information without eutra/eutra-nr/nr is invalid data?

Something as simple as an empty text file or some invalid/incorrect format.

For example, passing a text file with `this is not a capability file` to Q/QNR parsers is something I would expect a non-zero exit code for.

**Comment by HandyMenny** [comment]
That's quite complex, there are cases where the parser can extract valid result (but partial/incomplete) from invalid input too (e.g. sending ue cap enquiry + ue cap info or ue cap info with missing rat-types).
I would say it makes life much easier to have a "always send valid data" contract

**Comment by davwheat** [comment]
Fair enough. At the moment, I'm simply checking to see if the parser output contains no capability data, and if it doesn't then my API will return an error.

For reference:

```php
foreach ($output as &$out) {
    $outputLines = $out['output'];

    Arr::forget($outputLines, ['logType', 'parserVersion', 'timestamp', 'metadata']);

    // Error if one or more parser call outputs have no capability data
    if (count($outputLines) === 0) {
        $this->response = $this->response->withStatus(Response::HTTP_UNPROCESSABLE_ENTITY);

        return [
            'errors' => [
                'detail' => 'Parser failed to find any capability data in one or more of the provided log files.',
                'meta' => $out['output']
            ]
        ];
    }
}
```

It's annoying, since the general output fields are hardcoded in my code now, but I have tests that will complain if something isn't correct.
