### ISSUE TITLE
EUTRA and EUTRA-NR/NR logs not consistent in mod data

### ISSUE THREAD

**Issue by davwheat** [HandyMenny/uecapabilityparser#3]
In EUTRA parsing, the CSV returns `256qam` or `64qam`.

In EUTRA-NR or NR, the CSV returns `qam256` (LTE UL components return uppercase, e.g. `256QAM`).

This would potentially be a breaking change for apps already using the parser, but I think consistency is important.

This would require some processing of the signalling, I assume. It might be easier to change EUTRA to return qam256/64 instead of the other way around.

**Comment by HandyMenny** [comment]
Upper vs lower case is my fault, but qam256 vs 256qam comes from 3GPP:
https://www.sqimway.com/rrc_lte.html#FeatureSetUL-PerCC-r15
https://www.sqimway.com/rrc_nr.html#ModulationOrder

In any case good idea, the modulation should have been changed anyway, it's a string that is prone to errors like that
